config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :wineries do
    post 'favorite', on: :member
    post 'unfavorite', on: :member
    resources :reviews
  end
  resources :users
  resources :sessions

  root 'welcome#index'

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :winery
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :wineries
  has_many :reviews

  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates :name, presence: true

  scope :alphabetical, -> { order(:name) }
end

app/models/winery.rb
class Winery < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_many :reviews

  # ruby syntax for an anonymous function "lambdas"
  # we are passing the name of a function to be created and the action to the scope method
  scope :alphabetical, -> { order(:name) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # checks for current user, to be used with before_filter on controller actions
  # we may want to protect
  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end

  private
  def current_user
    # begin/rescue is used when you think an exception or error might be triggered
    begin
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    # telling ruby to only run the code for errors of this type
    rescue ActiveRecord::RecordNotFound
      session[:user_id] = nil
    end
  end

  def user_is_admin?
    current_user && current_user.admin
  end

  # helper_method makes the method available in the views as opposed to just in
  # the controllers that inherit from here
  helper_method :current_user
  helper_method :user_is_admin?

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  def show
  end

  # GET /reviews/new
  def new
    @winery = Winery.find(params[:winery_id])
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  def create
    @winery = Winery.find(params[:winery_id])
    @review = @winery.reviews.build(review_params)
    @review.user = current_user
    if @review.save
      redirect_to @winery
    else
      render :new
    end
  end

  # PATCH/PUT /reviews/1
  def update
    if @review.update(review_params)
      redirect_to @review, notice: 'Review was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:score, :content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to current_user, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid."
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index

    @users = User.alphabetical
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  def create
    @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to @user, notice: 'User was successfully created.'
      else
        render :new
      end
  end

  # GET /users/1/edit
  def edit
  end

  # # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @users = User.all
    @user.destroy
      redirect_to @users, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :location, :image, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/wineries_controller.rb
class WineriesController < ApplicationController
  before_action :set_winery, only: [:show, :edit, :update, :destroy, :favorite, :unfavorite]

  # GET /wineries
  def index
    @wineries = Winery.alphabetical
  end

  # GET /wineries/1
  def show
  end

  # GET /wineries/new
  def new
    @winery = Winery.new
  end

  # GET /wineries/1/edit
  def edit
  end

  # POST /wineries
  def create
    @winery = Winery.new(winery_params)
    if @winery.save
      redirect_to @winery, notice: 'Winery was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /wineries/1
  def update
    if @winery.update(winery_params)
      redirect_to @winery, notice: 'Winery was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /wineries/1
  # def destroy
  #   @winery.destroy
  #   redirect_to wineries_url, notice: 'Winery was successfully destroyed.'
  # end

  def favorite
    current_user.wineries << @winery
    redirect_to current_user
  end

  def unfavorite
    current_user.wineries.delete(@winery)
    redirect_to current_user
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_winery
      @winery = Winery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def winery_params
      params.require(:winery).permit(:name, :location, :website, :image, :phone_number, :visitors, :tours, :pets)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wineries_helper.rb
module WineriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wineries</title>
  <!-- REMOVED TURBOLINKS -->
  <script src="//cdnjs.cloudflare.com/ajax/libs/less.js/2.5.1/less.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="logo">
    <h1>Find yo' Wine</h1>
  </div>

  <div id="site_nav">
    <%= link_to "Wineries", wineries_path %> |
    <%= link_to "Users", users_path %> |
    <% if current_user %>
      Logged in under <%= current_user.email %>
      <%= link_to "Log Out", logout_path %>
    <% else %>
      <%= link_to "Sign Up", signup_path %> |
      <%= link_to "Log In", login_path %>
    <% end %>
  </div>

  <%= yield %>

</body>
</html>

app/views/ratings/_form.html.erb
<%= simple_form_for(@rating) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :score %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/reviews/_form.html.erb
<%= simple_form_for [@winery, @review] do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :score %>
    <%= f.input :content %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Score</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.score %></td>
        <td><%= review.content %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', winery_path(@winery) %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Score:</strong>
  <%= @review.score %>
</p>

<p>
  <strong>Content:</strong>
  <%= @review.content %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :location %>
    <%= f.input :image %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user %></td>
        <td><%= user.location %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user && current_user.admin %>
  <%= link_to 'New User', new_user_path %>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Location:</strong>
  <%= @user.location %>
</p>

<p>
  <img src= "<%=@user.image%>">
</p>

<p>
  <strong>Wineries <%= @user.name %> has visited:</strong>
  <ul class="user_wineries">
    <% for winery in @user.wineries %>
    <li>
      <%= link_to winery.name, winery_path(winery) %>
      <%= link_to "Remove", unfavorite_winery_path(winery), method: :post %>
    </li>
    <% end %>
  </ul>
</p>

<% if user_is_admin? %>
  <%= link_to 'Edit User', edit_user_path(@user) %> |
  <%= link_to 'Delete User', @user, method: :delete %> |
<% end %>
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/wineries/_form.html.erb
<%= simple_form_for(@winery) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :location %>
    <%= f.input :website %>
    <%= f.input :image %>
    <%= f.input :phone_number %>
    <%= f.input :visitors %>
    <%= f.input :tours %>
    <%= f.input :pets %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/wineries/edit.html.erb
<h1>Editing Winery</h1>

<%= render 'form' %>

<%= link_to 'Show', @winery %> |
<%= link_to 'Back', wineries_path %>

app/views/wineries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Wineries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
    </tr>
  </thead>

  <tbody>
    <% @wineries.each do |winery| %>
      <tr>
        <td><%= link_to winery.name, winery %></td>
        <td><%= winery.location %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user %>
  <%= link_to 'New Winery', new_winery_path %>
<% end %>  

app/views/wineries/new.html.erb
<h1>New Winery</h1>

<%= render 'form' %>

<%= link_to 'Back', wineries_path %>

app/views/wineries/show.html.erb
<p id="notice"><%= notice %></p> <%= link_to 'Back', wineries_path %>

<p>
  <strong>Name:</strong>
  <%= @winery.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @winery.location %>
</p>

<p>
  <strong>Website:</strong>
  <%= @winery.website %>
</p>

<p>
  <img src= "<%= @winery.image %>">
</p>

<p>
  <strong>Phone number:</strong>
  <%= @winery.phone_number %>
</p>

<p>
  <strong>Visitors:</strong>
  <%= @winery.visitors %>
</p>

<p>
  <strong>Tours:</strong>
  <%= @winery.tours %>
</p>

<p>
  <strong>Pets:</strong>
  <%= @winery.pets %>
</p>

<% if current_user %>
<p>
  <%= link_to 'Add a Review', new_winery_review_path(@winery) %>
  <%= link_to 'Add to Favorites', favorite_winery_path(@winery), method: :post %>
</p>
<% end %>

<p>
  <strong>Reviews:</strong>
  <ul>
  <% @winery.reviews.each do |review| %>
    <li><%= review.score %>/10 - <%= review.content %> (<%= review.user.name %>)</li>
  <% end %>
  </ul>
</p>

<% if user_is_admin? %>
  <%= link_to 'Edit Winery', edit_winery_path(@winery) %> |
  <%= link_to 'Delete Winery', @winery, method: :delete %> |
<% end %>